### ISSUE TITLE
Clarification of Use: What is <your-share-id-from-api>

### ISSUE THREAD

**Issue by GitPuffy** [nickstrand/Immich-python-slideshow#1]
I'm trying to give your script a try and am confused on a few things related to the Use section of the readme.

What are you trying to say to use when you wrote \<your-share-id-from-api\>?

I've created a shared album, shared it and recorded the URL.  I visit the URL and open an image and find the developer/debug information related to the "/api/asset/thumbnail..."  For me all of the value of "key" is the same as the URL that Immich provided for the share link. 

Would you help explain what it is that I should be looking for?

Thanks.

**Comment by nickstrand** [comment]
I'll try and revise the readme, but you do seem to be correct on the access key.  For now though what you need to do is get the share id from the api, and the access key is as you described.

To get the share ID run this (I used ubuntu terminal)
```curl -L 'https://photos.something.com/api/shared-link' -H 'Accept: application/json' -H 'x-api-key: apiKeyHereWithASpaceBeforeJustLikeThis'```

might be able to run with `| json_pp` 

```curl -L 'https://photos.something.com/api/shared-link' -H 'Accept: application/json' -H 'x-api-key: apiKeyHereWithASpaceBeforeJustLikeThis' | json_pp```

That will output the ID that you need, make sure you grab the right one for your album (album name shows in the json as well)

The access key is as you said, the end of the share link `https://photos.something.com/share/reallyLongShareIdHereblahblahblahblahblah`

```https://photos.something.com/random?random=${timestamp}&shareId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&accessKey=reallyLongShareIdHereblahblahblahblahblah&user=nstrand```

In the above link the /random is an endpoint for my nginx to redirect to the specific container, which I'll toss that config here for ya as a starter.

```
server {
    server_name photos.something.com;
    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/photos.something.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/photos.something.com/privkey.pem; # managed by Certbot
    ssl_dhparam /etc/nginx/ssl/dhparams.pem;

    location /random {
        proxy_pass http://internalphotos.something.com:8000;
        allow 192.168.0.0/24;
        deny all;

        proxy_set_header Host $http_host;
        proxy_set_header Connection        'close';
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-Host  $server_name;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    }
    location / {
        proxy_pass http://internalphotos.something.com:2283;
        allow all;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-Host  $server_name;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    }
}
```
